### ISSUE TITLE
Wowned not working

### ISSUE THREAD

**Issue by bahajan95** [namreeb/wowned#12]
![image](https://user-images.githubusercontent.com/13211961/34871787-b0ba5d32-f7b0-11e7-8aa6-f0881b5a4f0e.png)
i included auth_bypass.dll in path wow client 3.3.5a and runned wowned cmd it error
I'm not doing it right?
OS Win7 x32

**Comment by namreeb** [comment]
It looks from your screenshot like `auth_bypass.dll` and `wowned.exe` are not in the same directory.  They need to be.  Neither needs to be in your wow directory, though.  That said, the simplest thing is probably to put both files in your wow directory.  I am fairly certain that if you do that, you can simply double-click on `wowned.exe` and it will do the rest.

**Comment by bahajan95** [comment]
ok i try test
