### ISSUE TITLE
ASLR support

### ISSUE THREAD

**Issue by Artamedes** [namreeb/wowned#3]
It only works with atlantiss's exe https://mega.nz/#!n4ghTJAR!VImp8xll_-v7F-oKuzPvr5b1unKGTHQ8QlafFe-RrOc

**Comment by namreeb** [comment]
Thank you.  That is probably because they've disabled ASLR.  I may do another release with a fix to not require that.

**Comment by isawtrickzz** [comment]
List Of Servers Work ? For 3.3.5a and 4.3.4 cant find any server who works pls :D

**Comment by sunshitwowsucks** [comment]
Just go search and try yourself..

**Comment by namreeb** [comment]
This should be resolved with version 0.4.  Release information here: https://github.com/namreeb/wowned/releases/tag/0.4

**Comment by Tartian** [comment]
isn't working for me 0.4 in wow 4.3.4 with ASLR enabled

**Comment by namreeb** [comment]
What do you mean by "isn't working"?  What happens when you try?

**Comment by Tartian** [comment]
nothing, like the previous version
(Wow.exe never launch)

**Comment by ghost** [comment]
I tested on the latest version of Trinity 3.3.5 , Does not work

**Comment by Artamedes** [comment]
cause trinity fixed it... lol

**Comment by ghost** [comment]
Update the app wowned to work

It is possible?
